### ISSUE TITLE
The "mobility" style in the demo is broken. 

### ISSUE THREAD

**Issue by ARolek** [terranodo/tegola-osm#31]
Appears to be trying to fetch the style from an old location. 

<img width="510" alt="screen shot 2017-07-19 at 9 40 42 am" src="https://user-images.githubusercontent.com/667850/28378801-5a0b1ac4-6c66-11e7-98de-4e33f64aea52.png">

**Comment by jj0hns0n** [comment]
@PetersonGIS hasnt finished porting this style to the new schema. The old one is here https://github.com/PetersonGIS/Mobility

**Comment by ARolek** [comment]
@milafrerichs looks like you have it working, but the preview image is not yet in. Can you add it and then close this issue?
