### ISSUE TITLE
Natural Earth data has moved (again)

### ISSUE THREAD

**Issue by SomeoneElseOSM** [terranodo/tegola-osm#64]
https://github.com/go-spatial/tegola-osm/blob/master/natural_earth.sh#L59 et al define a location that doesn't work any more.   The locations at the gist linked from https://github.com/nvkelso/natural-earth-vector/issues/581#issuecomment-916250782 seem to be the preferred ones now.  Example:

    https://naturalearth.s3.amazonaws.com/10m_cultural/ne_10m_admin_0_boundary_lines_land.zip

**Comment by ARolek** [comment]
Thanks for the report! Can you send in a PR?

**Comment by PraveenAlexis** [comment]
"https://naturalearth.s3.amazonaws.com/110m_cultural/ne_110m_admin_0_boundary_lines_land.zip"
    "https://naturalearth.s3.amazonaws.com/110m_cultural/ne_110m_admin_0_countries.zip"
    "https://naturalearth.s3.amazonaws.com/110m_cultural/ne_110m_admin_1_states_provinces_lines.zip"
    "https://naturalearth.s3.amazonaws.com/110m_cultural/ne_110m_populated_places.zip"
    "https://naturalearth.s3.amazonaws.com/110m_physical/ne_110m_coastline.zip"
    "https://naturalearth.s3.amazonaws.com/110m_physical/ne_110m_geography_marine_polys.zip"
    "https://naturalearth.s3.amazonaws.com/110m_physical/ne_110m_geography_regions_polys.zip"
    "https://naturalearth.s3.amazonaws.com/110m_physical/ne_110m_rivers_lake_centerlines.zip"
    "https://naturalearth.s3.amazonaws.com/110m_physical/ne_110m_lakes.zip"
    "https://naturalearth.s3.amazonaws.com/110m_physical/ne_110m_glaciated_areas.zip"
    "https://naturalearth.s3.amazonaws.com/110m_physical/ne_110m_land.zip"
    "https://naturalearth.s3.amazonaws.com/110m_physical/ne_110m_ocean.zip"
    "https://naturalearth.s3.amazonaws.com/50m_cultural/ne_50m_admin_0_boundary_lines_land.zip"
    "https://naturalearth.s3.amazonaws.com/50m_cultural/ne_50m_admin_0_boundary_lines_disputed_areas.zip"
    "https://naturalearth.s3.amazonaws.com/50m_cultural/ne_50m_admin_0_boundary_lines_maritime_indicator.zip"
    "https://naturalearth.s3.amazonaws.com/50m_cultural/ne_50m_admin_0_countries.zip"
    "https://naturalearth.s3.amazonaws.com/50m_cultural/ne_50m_admin_0_map_subunits.zip"
    "https://naturalearth.s3.amazonaws.com/50m_cultural/ne_50m_admin_1_states_provinces_lakes.zip" 
    "https://naturalearth.s3.amazonaws.com/50m_cultural/ne_50m_admin_1_states_provinces_lines.zip"
    "https://naturalearth.s3.amazonaws.com/50m_cultural/ne_50m_populated_places.zip"
    "https://naturalearth.s3.amazonaws.com/50m_physical/ne_50m_geographic_lines.zip"
    "https://naturalearth.s3.amazonaws.com/50m_physical/ne_50m_coastline.zip"
    "https://naturalearth.s3.amazonaws.com/50m_physical/ne_50m_antarctic_ice_shelves_lines.zip"
    "https://naturalearth.s3.amazonaws.com/50m_physical/ne_50m_antarctic_ice_shelves_polys.zip"
    "https://naturalearth.s3.amazonaws.com/50m_physical/ne_50m_geography_marine_polys.zip"
    "https://naturalearth.s3.amazonaws.com/50m_physical/ne_50m_geography_regions_elevation_points.zip"
    "https://naturalearth.s3.amazonaws.com/50m_physical/ne_50m_geography_regions_polys.zip"
    "https://naturalearth.s3.amazonaws.com/50m_physical/ne_50m_rivers_lake_centerlines_scale_rank.zip"
    "https://naturalearth.s3.amazonaws.com/50m_physical/ne_50m_rivers_lake_centerlines.zip"
    "https://naturalearth.s3.amazonaws.com/50m_physical/ne_50m_lakes.zip"
    "https://naturalearth.s3.amazonaws.com/50m_physical/ne_50m_glaciated_areas.zip"
    "https://naturalearth.s3.amazonaws.com/50m_physical/ne_50m_land.zip"
    "https://naturalearth.s3.amazonaws.com/50m_physical/ne_50m_ocean.zip"
    "https://naturalearth.s3.amazonaws.com/10m_cultural/ne_10m_admin_0_boundary_lines_land.zip" 
    "https://naturalearth.s3.amazonaws.com/10m_cultural/ne_10m_admin_0_boundary_lines_disputed_areas.zip" 
    "https://naturalearth.s3.amazonaws.com/10m_cultural/ne_10m_parks_and_protected_lands.zip" 
    "https://naturalearth.s3.amazonaws.com/10m_cultural/ne_10m_admin_0_boundary_lines_map_units.zip" 
    "https://naturalearth.s3.amazonaws.com/10m_cultural/ne_10m_admin_0_boundary_lines_maritime_indicator.zip"
    "https://naturalearth.s3.amazonaws.com/10m_cultural/ne_10m_admin_0_label_points.zip"
    "https://naturalearth.s3.amazonaws.com/10m_cultural/ne_10m_admin_0_countries.zip" 
    "https://naturalearth.s3.amazonaws.com/10m_cultural/ne_10m_admin_0_map_subunits.zip"
    "https://naturalearth.s3.amazonaws.com/10m_cultural/ne_10m_admin_1_label_points.zip"   
    "https://naturalearth.s3.amazonaws.com/10m_cultural/ne_10m_admin_1_states_provinces_lines.zip" 
    "https://naturalearth.s3.amazonaws.com/10m_cultural/ne_10m_populated_places.zip" 
    "https://naturalearth.s3.amazonaws.com/10m_cultural/ne_10m_roads.zip" 
    "https://naturalearth.s3.amazonaws.com/10m_cultural/ne_10m_urban_areas.zip" 
    "https://naturalearth.s3.amazonaws.com/10m_physical/ne_10m_geographic_lines.zip" 
    "https://naturalearth.s3.amazonaws.com/10m_physical/ne_10m_coastline.zip" 
    "https://naturalearth.s3.amazonaws.com/10m_physical/ne_10m_antarctic_ice_shelves_lines.zip" 
    "https://naturalearth.s3.amazonaws.com/10m_physical/ne_10m_antarctic_ice_shelves_polys.zip" 
    "https://naturalearth.s3.amazonaws.com/10m_physical/ne_10m_geography_marine_polys.zip" 
    "https://naturalearth.s3.amazonaws.com/10m_physical/ne_10m_geography_regions_elevation_points.zip" 
    "https://naturalearth.s3.amazonaws.com/10m_physical/ne_10m_geography_regions_points.zip" 
    "https://naturalearth.s3.amazonaws.com/10m_physical/ne_10m_geography_regions_polys.zip"
    "https://naturalearth.s3.amazonaws.com/10m_physical/ne_10m_rivers_north_america.zip"
    "https://naturalearth.s3.amazonaws.com/10m_physical/ne_10m_rivers_europe.zip"
    "https://naturalearth.s3.amazonaws.com/10m_physical/ne_10m_rivers_lake_centerlines_scale_rank.zip"     
    "https://naturalearth.s3.amazonaws.com/10m_physical/ne_10m_rivers_lake_centerlines.zip" 
    "https://naturalearth.s3.amazonaws.com/10m_physical/ne_10m_playas.zip"
    "https://naturalearth.s3.amazonaws.com/10m_physical/ne_10m_reefs.zip" 
    "https://naturalearth.s3.amazonaws.com/10m_physical/ne_10m_lakes_historic.zip" 
    "https://naturalearth.s3.amazonaws.com/10m_physical/ne_10m_lakes_north_america.zip"
    "https://naturalearth.s3.amazonaws.com/10m_physical/ne_10m_lakes_europe.zip"
    "https://naturalearth.s3.amazonaws.com/10m_physical/ne_10m_lakes.zip" 
    "https://naturalearth.s3.amazonaws.com/10m_physical/ne_10m_glaciated_areas.zip" 
    "https://naturalearth.s3.amazonaws.com/10m_physical/ne_10m_land.zip"
    "https://naturalearth.s3.amazonaws.com/10m_physical/ne_10m_minor_islands.zip" 
    "https://naturalearth.s3.amazonaws.com/10m_physical/ne_10m_ocean.zip"
