### ISSUE TITLE
Software License?

### ISSUE THREAD

**Issue by SebastianDa** [terranodo/tegola-osm#66]
Hello Tegola-Team,

thanks for the great job and the contribution to the OSM World. I noticed that this repository doesn't contain a license. I guess it should be licensed under MIT as your main repository (https://github.com/go-spatial/tegola/blob/v0.15.x/LICENSE.md). Am i right? Can you add a license to clarify this?

**Comment by ARolek** [comment]
@SebastianDa thanks for bringing that up. I have added a MIT license file.
